blank_issues_enabled: false
contact_links:
  - name: uBO Lite Community Support
    url: https://github.com/uBlockOrigin/uBOL-home/discussions
    about: Please ask and answer questions here. Do not ask question in the issue tracker.
