name: uBO Lite release

on: workflow_dispatch

permissions:
  contents: read

# I used the following project as template to get started:
# https://github.com/dessant/search-by-image/blob/master/.github/workflows/ci.yml

jobs:
  build:
    permissions:
      contents: write # for creating release
    name: Build packages
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: recursive
      - name: Locate uBO repo
        run: |
          UBOL_REPO_DIR=$(pwd)
          UBLOCK_REPO_DIR="$UBOL_REPO_DIR/uBlock"
          echo "UBLOCK_REPO_DIR=$UBLOCK_REPO_DIR" >> $GITHUB_ENV
      # Version, time-based
      - name: Create unique time-based version
        run: |
          TAGNAME=uBOLite_$(date -u "+%Y").$(date -u "+%-m*100+%-d" | bc).$(date -u "+%H*100+%M" | bc)
          echo "TAGNAME=$TAGNAME" >> $GITHUB_ENV
          echo "Version: $TAGNAME"
      # Chromium
      - name: Build Chromium uBOLite
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          UBOL_REPO_DIR=$(pwd)
          cd $UBLOCK_REPO_DIR
          tools/make-mv3.sh chromium ${{ env.TAGNAME }} before=$UBOL_REPO_DIR
          echo "CHROMIUM_PACKAGE=${{ env.TAGNAME }}.chromium.mv3.zip" >> $GITHUB_ENV
          cd - > /dev/null
          rm -rf chromium
          mv "$UBLOCK_REPO_DIR/dist/build/uBOLite.chromium" chromium
      # Edge
      - name: Build Edge uBOLite
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          UBOL_REPO_DIR=$(pwd)
          cd $UBLOCK_REPO_DIR
          tools/make-mv3.sh edge ${{ env.TAGNAME }}
          echo "EDGE_PACKAGE=${{ env.TAGNAME }}.edge.mv3.zip" >> $GITHUB_ENV
          cd - > /dev/null
      # Safari
      - name: Build Safari uBOLite
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          UBOL_REPO_DIR=$(pwd)
          cd $UBLOCK_REPO_DIR
          tools/make-mv3.sh safari ${{ env.TAGNAME }}
          echo "SAFARI_PACKAGE=${{ env.TAGNAME }}.safari.mv3.zip" >> $GITHUB_ENV
          cd - > /dev/null
      - name: Commit uBOLite MV3 package files
        # https://github.com/marketplace/actions/github-action-for-committing-changes-to-a-repository
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "[workflow] Update uBOLite MV3 package files for ${{ env.TAGNAME }}"
      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAGNAME }}
          name: ${{ env.TAGNAME }}
          prerelease: true
          body: |
            **uBO Lite** (uBOL), an [MV3 API-based](https://developer.chrome.com/docs/extensions/mv3/intro/) content blocker.
            
            - [Synopsis](https://github.com/uBlockOrigin/uBOL-issues#readme)
            - [Documentation](https://github.com/uBlockOrigin/uBOL-home/wiki)
            
            ## Release notes
            
            - Updated filter lists
            - [Commit history](https://github.com/uBlockOrigin/uBOL-home/commits/${{ env.TAGNAME }})
            
            ---
            
            ## Installation
            
            - Chromium-based browsers: Install from the [Chrome Web Store](https://chrome.google.com/webstore/detail/ddkjiahejlhfcafbddmgiahcphecmpfh)
            - Microsoft Edge: Install from the [Edge Add-ons store](https://microsoftedge.microsoft.com/addons/detail/ublock-origin-lite/cimighlppcgcoapaliogpjjdehbnofhn)
            - Safari: Install from the [Safari App Store](https://apps.apple.com/us/app/ublock-origin-lite/id6745342698)
          files: |
            ${{ env.UBLOCK_REPO_DIR }}/dist/build/${{ env.CHROMIUM_PACKAGE }}
            ${{ env.UBLOCK_REPO_DIR }}/dist/build/${{ env.EDGE_PACKAGE }}
            ${{ env.UBLOCK_REPO_DIR }}/dist/build/${{ env.SAFARI_PACKAGE }}
