name: uBO Lite Safari

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write # for creating release
    name: Build packages
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: recursive
      - name: Locate uBO repo
        run: |
          UBOL_REPO_DIR=$(pwd)
          UBLOCK_REPO_DIR="$UBOL_REPO_DIR/uBlock"
          echo "UBLOCK_REPO_DIR=$UBLOCK_REPO_DIR" >> $GITHUB_ENV
      # Version, time-based
      - name: Create unique time-based version
        run: |
          TAGNAME=uBOLite_$(date -u "+%Y").$(date -u "+%-m*100+%-d" | bc).$(date -u "+%H*100+%M" | bc)
          echo "TAGNAME=$TAGNAME" >> $GITHUB_ENV
          echo "Version: $TAGNAME"
      # Safari
      - name: Build Safari uBOLite
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          UBOL_REPO_DIR=$(pwd)
          cd $UBLOCK_REPO_DIR
          tools/make-mv3.sh safari ${{ env.TAGNAME }} before=$UBOL_REPO_DIR
          cd - > /dev/null
      - name: Create GitHub Safari release
        id: create_safari_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAGNAME }}-safari
          name: ${{ env.TAGNAME }}-safari
          prerelease: true
          body: |
            **uBO Lite** (uBOL), an [MV3 API-based](https://developer.chrome.com/docs/extensions/mv3/intro/) content blocker.
            
            - [Synopsis](https://github.com/uBlockOrigin/uBOL-issues#readme)
            - [Documentation](https://github.com/uBlockOrigin/uBOL-home/wiki)
            
            ## Release notes
            
            - Updated filter lists
                        
          files: |
            ${{ env.UBLOCK_REPO_DIR }}/dist/build/${{ env.TAGNAME }}.safari.mv3.zip
